### ISSUE TITLE
User customized rate limit ?

### ISSUE THREAD

**Issue by harshraj22** [long2ice/fastapi-limiter#26]
I want to have a subscription based api service. there are 3 types of subscription:
Free: 10 api calls per 24hour
Basic: 30 api calls per 24hour
Advanced: 80 api calls per 24hour.

Along with the request body, suppose the detaiils about the subscription is also available. Can such scenario be handled by your library ?
I am using fastapi, and I would prefer using a library than writing my own rate limiter using reddis.

**Comment by HutchNunez** [comment]
Why does this not work as expected? The RateLimit is not being applied ...

```
def dynamic_rate_limiter(request: Request, response: Response):
    return RateLimiter(times=1, seconds=60)


@router.get(
    "/v1/dummy",
    dependencies=[Depends(dynamic_rate_limiter)],
)
def get_dummy(
):
    return {"dummy": "dummy"}

```
