### ISSUE TITLE
Unable to install fastapi-limiter on Linux machine

### ISSUE THREAD

**Issue by waconde** [long2ice/fastapi-limiter#29]
Help...

When I installed fastapi-limiter using the python virtual environment on a Windows machine, everything worked fine.
But when I used the python virtual environment on Linux machine to install fastapi-limiter, it gave me an error:
![Linux error info](https://user-images.githubusercontent.com/28390161/223696716-34de323a-0d9c-4916-8c69-81c8d8bbf8c1.jpg)

My Version of Python is both 3.6.15.

I tried my best to switching agents, switching warehouse, or switching to other Linux machines, but nothing worked. It is too strange that any Linux machine I can find would report such errors. 
I'm looking forward to your help!

**Comment by stevleibelt** [comment]
@waconde 

pretty strange that it is working on windows. Fastapi-Limiter supports the following python version: [Python >=3.7, <4.0](https://github.com/long2ice/fastapi-limiter/blob/master/pyproject.toml#L20)

Please check your python version on both machines again and close the ticket if my answer could solve your issue.

Cheers,
Stev

**Comment by waconde** [comment]
> @waconde
> 
> pretty strange that it is working on windows. Fastapi-Limiter supports the following python version: [Python >=3.7, <4.0](https://github.com/long2ice/fastapi-limiter/blob/master/pyproject.toml#L20)
> 
> Please check your python version on both machines again and close the ticket if my answer could solve your issue.
> 
> Cheers, Stev

oh…so it was just an accident that I was able to install it successfully on a windows machine, The fundamental problem is the Python version. thank you for your answer!
