### ISSUE TITLE
[feature]Two RateLimiter's co-exist

### ISSUE THREAD

**Issue by zhiboz** [long2ice/fastapi-limiter#3]
Is it feasible to support two RateLimiter's at the same time? For instance, 

`[Depends(RateLimiter(times=2, seconds=5)), Depends(RateLimiter(times=100, hours =24))]`

to limit max 2 hits every 5 seconds AND max 100 hits per day from the same `ip`. very much appreciated.

**Comment by long2ice** [comment]
Which is a normal requirement, I will think about it.

**Comment by long2ice** [comment]
Current you can use custom `identifier` param for each dependency.

**Comment by BookerLoL** [comment]
I think it would be a nice feature to add if possible. Would match functionalities similar to what other API limiters can do, ex: Flask-Limiter

**Comment by long2ice** [comment]
Supported
