### ISSUE TITLE
how to handle connection timeout?

### ISSUE THREAD

**Issue by stevleibelt** [long2ice/fastapi-limiter#30]
Hello,

first of all, thank you for this library which had saved me time to "just implement rate limitation" :-).

I am currently struggling with the problem to handle connection timeouts.

Simple said, if I try to connect to non existing redis host, I don't get an error message. All I get is a hanging application for more than 10 Minutes.
I would prefer to throw an HTTPException to send my client a "Internal server error" or "Service temporary not available" message.

I could not solve this issue so far. Following my current way how I connect to the redis server.

```python
@app.on_event("startup")
async def startup():

    try:
        redis_connection = redis.Redis(
            host=os.getenv('REDIS_HOST'),
            port=int(os.getenv('REDIS_PORT')),
            db=int(os.getenv('REDIS_DATABASE')),
            socket_connect_timeout=5,   # socket_connect_timeout applies only to blocking during the initial TCP handshake
            socket_timeout=5,           # socket_timeout applies to all blocking socket operations, ref: https://github.com/redis/redis-py/issues/722#issuecomment-607509357
            health_check_interval=10
        )

        logging.debug('Redis connection established',\
                      extra={'context': {'connection_parameters':\
                                             'host >>{0}<<, port >>{1}<<, db >>{2}<<.'.format(os.getenv('REDIS_HOST'),\
                                                                                              os.getenv('REDIS_PORT'),\
                                                                                              os.getenv('REDIS_DATABASE'\
                                                                                                        ))}})
    except redis.ConnectionError as exception:
        log_excepted_exception(exception, 'startup', 500, 'redis_connection_error', 'SYSTEM')
    except redis.TimeoutError as exception:
        log_excepted_exception(exception, 'startup', 500, 'redis_timeout_error', 'SYSTEM')

    await FastAPILimiter.init(
        prefix='fastapi_limiter_',
        redis=redis_connection
    )
```

Non of the three settings (`socket_connect_timeout`, `socket_timeout` or `health_check_interval`) could stop the application from "hanging".

I hope there is a big missing link I ran into. Have you ever tried to implement my kind of requirements?

Thanks in advance,
Stev

**Comment by tcrasset** [comment]
I'm not sure what you are trying to achieve.

If you want to let your users know that your FastAPI application is not setup, this is a FastAPI issue. `startup` events are setup before FastAPI accepts any requests, so you might need throw your own custom error upon catching the redis errors.

If you want to retry your connection to redis if the initial connection failed, you can use `Retry` and any kind of backoff.
See below for an example.

```python
from redis.retry import Retry
from redis.backoff import ExponentialBackoff

import redis.asyncio as redis
from fastapi import Depends

app = FastApi()

@app.on_event("startup")
async def startup():
	url = "redis://..."
    retry = Retry(backoff=ExponentialBackoff(), retries=10)
    redis_instance = await redis.from_url(url, encoding="utf-8", decode_responses=True, retry=retry)
    await FastAPILimiter.init(redis_instance)
```
If you want to make FastApiLimiter work after redis went down and back up again, you'll have to wait until https://github.com/long2ice/fastapi-limiter/pull/33 gets merged.

**Comment by stevleibelt** [comment]
@tcrasset thank you very much for all your shared knowledge.

I will give it a try and will give feedback if useful.

Best regards!
