### ISSUE TITLE
Rare failure mode

### ISSUE THREAD

**Issue by hardbyte** [long2ice/fastapi-limiter#6]
Looking at the core in [fastapi_limiter/depends.py#L35-L42](https://github.com/long2ice/fastapi-limiter/blob/master/fastapi_limiter/depends.py#L35-L42):
```python
        p = redis.pipeline()
        p.incrby(key, 1)
        p.pttl(key)
        num, pexpire = await p.execute()
        if num == 1:
            await redis.pexpire(key, self.milliseconds)
        if num > self.times:
            return await callback(request, pexpire)
```

In the extremely rare case that the process fails between incrementing the value with `p.execute()` and setting the ttl with `redis.pexpire` the key won't actually have a time to live set. The next request will increment the count, but as `num` will already be greater than 1 the expiry won't get set... so after `self.times` requests all following requests will count as exceeding the rate limit.

**Comment by hardbyte** [comment]
A possible solution might be to first check if the key exists, and if it doesn't create it with the count of zero and set the TTL.

**Comment by long2ice** [comment]
Maybe we should use transaction said in https://aioredis.readthedocs.io/en/v1.3.0/mixins.html#transaction-commands instead of pipeline

**Comment by hardbyte** [comment]
It looks to me like that would work - assuming aioredis exposes the `watch` command from https://redis.io/topics/transactions#cas

**Comment by hardbyte** [comment]
Issue is still present right? Is this being closed as "won't fix"?

**Comment by long2ice** [comment]
Fixed in https://github.com/long2ice/fastapi-limiter/commit/f7d572051916fb20c65ec68407e63f1ca34f6001

**Comment by hardbyte** [comment]
As far as I can tell that change doesn't address the issue. 

It's the second redis call that sets the ttl on the key (iff num is 1). If that second transaction is missed due to computers being computers, the rate limiter is *forever* going to deny all future requests once the _per period_ limit is reached.

**Comment by long2ice** [comment]
Could you give a PR and tests?

**Comment by hardbyte** [comment]
@long2ice do you want to reopen this issue? Hopefully my diagrams help to explain how a service using fastapi-limiter can get into an irrecoverable state.

Do you have any thoughts on my proposed solution?

**Comment by long2ice** [comment]
Could get exists by `num = 1` after run `incr`?

**Comment by hardbyte** [comment]
I'm not sure what you mean? In the current protocol or in my proposal?

**Comment by Alexander-N** [comment]
How about setting the TTL every time in the transaction? That should be safe and doesn't need the extra roundtrip. Maybe I'm missing something but doesn't it make sense to reset the TTL for every request?

Not familiar with aioredis but something like this:
```python
tr = redis.multi_exec()
tr.incrby(key, 1)
tr.pexpire(key, self.milliseconds)
num, _ = await tr.execute()
```

**Comment by hardbyte** [comment]
That would prevent the failure condition... but it would stop being a rate limiter :-P

**Comment by Alexander-N** [comment]
Oh, thats right :smile:. What's missing is that one has to use a separate key for each time interval as in https://redis.io/commands/incr/#pattern-rate-limiter-1

**Comment by hardbyte** [comment]
Nice work @long2ice https://github.com/long2ice/fastapi-limiter/commit/1fd34df8ff440ee604e43810738253ea23be9abf looks like a solid fix.
