### ISSUE TITLE
Multiple rate limiters does not work properly?

### ISSUE THREAD

**Issue by BookerLoL** [long2ice/fastapi-limiter#8]
Using only 1 RateLimiter works fine, however multiple RateLimiters there are issues?

**Only the first RateLimiter is kind of working but the second one is not triggered?**

```python
@router.get("/time", dependencies=[Depends(RateLimiter(times=3, seconds=5)), Depends(RateLimiter(times=5, hours=1))])
```
The first RateLimiter **only limits 2 times** instead of 3 times and the second RateLimiter is not properly being checked until later on? Changing the amount of times will still have similar effects where you can only do less than the amount of times allowed. 

If you change it so that the RateLimiter has a greater time limit first, like this
```python
@router.get("/time", dependencies=[Depends(RateLimiter(times=10, hours=1)), Depends(RateLimiter(times=3, seconds=5))])
```
This will only work for the first RateLimiter but not the second one. 

Edit:
Whenever I try to change the path url for a specific route and restart the API, the route is still affected by the RateLimiter from before? 

I have to flush the data from the database to fix the issue.

Edit 2:
I guess that issue for why less calls happen is that it's calling the second rate limiter and incrementing if it passes?

Edit 3:
One possible idea for multiple RateLimiters could be something like this
```python
dependencies=[Depends(RaterLimiters(RateLimiter(...), RateLimiter(...)))]
```
This class could grab each identifier, see if there are duplicates, if there are duplicates then sort then based on time then increment each unique identifier?

**Comment by long2ice** [comment]
Did you install latest from source? I don't release yet.

**Comment by BookerLoL** [comment]
Oh let me try by downloading the source.

**Comment by BookerLoL** [comment]
Oh sorry for writing a big issue. Yeah it wasn't on release and that's probably why. 
I tested it and it seemed to work on my machine. 
```python
@app.get(
    "/multiple",
    dependencies=[
        Depends(RateLimiter(times=10, seconds=10)),
        Depends(RateLimiter(times=15, minutes=1)),
        Depends(RateLimiter(times=40, hours=1)),
    ],
)
```
This works correctly which is awesome!

I did notice weird behavior when you do something like this: 
```python
@app.get(
    "/multiple",
    dependencies=[
        Depends(RateLimiter(times=10, hours=1)),
        Depends(RateLimiter(times=5, seconds=3)),
    ],
)
```
If you don't exceed the second limit, it does 10 times per hour. 
If you exceed the second limit, you can only do 5 times per hour.

**I guess it should be noted that order matters**

**Comment by long2ice** [comment]
I sort limiters by seconds/times, just try again

**Comment by BookerLoL** [comment]
```python
@app.get(
    "/multiple",
    dependencies=[
        Depends(RateLimiter(times=10, hours=1)),
        Depends(RateLimiter(times=5, seconds=5)),
    ],
)
```
I can run it 5 times, wait, only run it 3 more times later.

**Comment by long2ice** [comment]
My bad, the update later is incorrect, as you said, should be noted that order matters
